module IntlPhoneInput.Svg
    exposing
        ( arrow
        , flag
        )

import Dict exposing (Dict)
import IntlPhoneInput.Flags as Flags
import Svg exposing (Svg, polygon, svg)
import Svg.Attributes exposing (..)


arrow : Svg msg
arrow =
    let
        rotation =
            "90"
    in
    svg [ width "100%", height "100%", viewBox "0 0 20 20", style <| "transform: rotate(" ++ rotation ++ "deg);" ]
        [ polygon [ points "0 0, 0 20, 16 10" ] []
        ]


flag : String -> Svg msg
flag isoCode =
    Dict.get isoCode flags
        |> Maybe.withDefault Flags.unknownFlag


flags : Dict String (Svg msg)
flags =
    Dict.fromList
        [ ( "AD", Flags.adFlag )
        , ( "AE", Flags.aeFlag )
        , ( "AF", Flags.afFlag )
        , ( "AG", Flags.agFlag )
        , ( "AI", Flags.aiFlag )
        , ( "AL", Flags.alFlag )
        , ( "AM", Flags.amFlag )
        , ( "AO", Flags.aoFlag )
        , ( "AR", Flags.arFlag )
        , ( "AS", Flags.asFlag )
        , ( "AT", Flags.atFlag )
        , ( "AU", Flags.auFlag )
        , ( "AW", Flags.awFlag )
        , ( "AX", Flags.axFlag )
        , ( "AZ", Flags.azFlag )
        , ( "BA", Flags.baFlag )
        , ( "BB", Flags.bbFlag )
        , ( "BD", Flags.bdFlag )
        , ( "BE", Flags.beFlag )
        , ( "BF", Flags.bfFlag )
        , ( "BG", Flags.bgFlag )
        , ( "BH", Flags.bhFlag )
        , ( "BI", Flags.biFlag )
        , ( "BJ", Flags.bjFlag )
        , ( "BL", Flags.blFlag )
        , ( "BM", Flags.bmFlag )
        , ( "BN", Flags.bnFlag )
        , ( "BO", Flags.boFlag )
        , ( "BQ", Flags.bqFlag )
        , ( "BR", Flags.brFlag )
        , ( "BS", Flags.bsFlag )
        , ( "BT", Flags.btFlag )
        , ( "BW", Flags.bwFlag )
        , ( "BY", Flags.byFlag )
        , ( "BZ", Flags.bzFlag )
        , ( "CA", Flags.caFlag )
        , ( "CC", Flags.ccFlag )
        , ( "CD", Flags.cdFlag )
        , ( "CF", Flags.cfFlag )
        , ( "CG", Flags.cgFlag )
        , ( "CH", Flags.chFlag )
        , ( "CI", Flags.ciFlag )
        , ( "CK", Flags.ckFlag )
        , ( "CL", Flags.clFlag )
        , ( "CM", Flags.cmFlag )
        , ( "CN", Flags.cnFlag )
        , ( "CO", Flags.coFlag )
        , ( "CR", Flags.crFlag )
        , ( "CU", Flags.cuFlag )
        , ( "CV", Flags.cvFlag )
        , ( "CW", Flags.cwFlag )
        , ( "CX", Flags.cxFlag )
        , ( "CY", Flags.cyFlag )
        , ( "CZ", Flags.czFlag )
        , ( "DE", Flags.deFlag )
        , ( "DJ", Flags.djFlag )
        , ( "DK", Flags.dkFlag )
        , ( "DM", Flags.dmFlag )
        , ( "DO", Flags.doFlag )
        , ( "DZ", Flags.dzFlag )
        , ( "EC", Flags.ecFlag )
        , ( "EE", Flags.eeFlag )
        , ( "EG", Flags.egFlag )
        , ( "EH", Flags.ehFlag )
        , ( "ER", Flags.erFlag )
        , ( "ES", Flags.esFlag )
        , ( "ET", Flags.etFlag )
        , ( "FI", Flags.fiFlag )
        , ( "FJ", Flags.fjFlag )
        , ( "FK", Flags.fkFlag )
        , ( "FM", Flags.fmFlag )
        , ( "FO", Flags.foFlag )
        , ( "FR", Flags.frFlag )
        , ( "GA", Flags.gaFlag )
        , ( "GB", Flags.gbFlag )
        , ( "GD", Flags.gdFlag )
        , ( "GE", Flags.geFlag )
        , ( "GF", Flags.gfFlag )
        , ( "GG", Flags.ggFlag )
        , ( "GH", Flags.ghFlag )
        , ( "GI", Flags.giFlag )
        , ( "GL", Flags.glFlag )
        , ( "GM", Flags.gmFlag )
        , ( "GN", Flags.gnFlag )
        , ( "GP", Flags.gpFlag )
        , ( "GQ", Flags.gqFlag )
        , ( "GR", Flags.grFlag )
        , ( "GT", Flags.gtFlag )
        , ( "GU", Flags.guFlag )
        , ( "GW", Flags.gwFlag )
        , ( "GY", Flags.gyFlag )
        , ( "HK", Flags.hkFlag )
        , ( "HN", Flags.hnFlag )
        , ( "HR", Flags.hrFlag )
        , ( "HT", Flags.htFlag )
        , ( "HU", Flags.huFlag )
        , ( "ID", Flags.idFlag )
        , ( "IE", Flags.ieFlag )
        , ( "IL", Flags.ilFlag )
        , ( "IM", Flags.imFlag )
        , ( "IN", Flags.inFlag )
        , ( "IO", Flags.ioFlag )
        , ( "IQ", Flags.iqFlag )
        , ( "IR", Flags.irFlag )
        , ( "IS", Flags.isFlag )
        , ( "IT", Flags.itFlag )
        , ( "JE", Flags.jeFlag )
        , ( "JM", Flags.jmFlag )
        , ( "JO", Flags.joFlag )
        , ( "JP", Flags.jpFlag )
        , ( "KE", Flags.keFlag )
        , ( "KG", Flags.kgFlag )
        , ( "KH", Flags.khFlag )
        , ( "KI", Flags.kiFlag )
        , ( "KM", Flags.kmFlag )
        , ( "KN", Flags.knFlag )
        , ( "KP", Flags.kpFlag )
        , ( "KR", Flags.krFlag )
        , ( "KW", Flags.kwFlag )
        , ( "KY", Flags.kyFlag )
        , ( "KZ", Flags.kzFlag )
        , ( "LA", Flags.laFlag )
        , ( "LB", Flags.lbFlag )
        , ( "LC", Flags.lcFlag )
        , ( "LI", Flags.liFlag )
        , ( "LK", Flags.lkFlag )
        , ( "LR", Flags.lrFlag )
        , ( "LS", Flags.lsFlag )
        , ( "LT", Flags.ltFlag )
        , ( "LU", Flags.luFlag )
        , ( "LV", Flags.lvFlag )
        , ( "LY", Flags.lyFlag )
        , ( "MA", Flags.maFlag )
        , ( "MC", Flags.mcFlag )
        , ( "MD", Flags.mdFlag )
        , ( "ME", Flags.meFlag )
        , ( "MF", Flags.mfFlag )
        , ( "MG", Flags.mgFlag )
        , ( "MH", Flags.mhFlag )
        , ( "MK", Flags.mkFlag )
        , ( "ML", Flags.mlFlag )
        , ( "MM", Flags.mmFlag )
        , ( "MN", Flags.mnFlag )
        , ( "MO", Flags.moFlag )
        , ( "MP", Flags.mpFlag )
        , ( "MQ", Flags.mqFlag )
        , ( "MR", Flags.mrFlag )
        , ( "MS", Flags.msFlag )
        , ( "MT", Flags.mtFlag )
        , ( "MU", Flags.muFlag )
        , ( "MV", Flags.mvFlag )
        , ( "MW", Flags.mwFlag )
        , ( "MX", Flags.mxFlag )
        , ( "MY", Flags.myFlag )
        , ( "MZ", Flags.mzFlag )
        , ( "NA", Flags.naFlag )
        , ( "NC", Flags.ncFlag )
        , ( "NE", Flags.neFlag )
        , ( "NF", Flags.nfFlag )
        , ( "NG", Flags.ngFlag )
        , ( "NI", Flags.niFlag )
        , ( "NL", Flags.nlFlag )
        , ( "NO", Flags.noFlag )
        , ( "NP", Flags.npFlag )
        , ( "NR", Flags.nrFlag )
        , ( "NU", Flags.nuFlag )
        , ( "NZ", Flags.nzFlag )
        , ( "OM", Flags.omFlag )
        , ( "PA", Flags.paFlag )
        , ( "PE", Flags.peFlag )
        , ( "PF", Flags.pfFlag )
        , ( "PG", Flags.pgFlag )
        , ( "PH", Flags.phFlag )
        , ( "PK", Flags.pkFlag )
        , ( "PL", Flags.plFlag )
        , ( "PM", Flags.pmFlag )
        , ( "PR", Flags.prFlag )
        , ( "PS", Flags.psFlag )
        , ( "PT", Flags.ptFlag )
        , ( "PW", Flags.pwFlag )
        , ( "PY", Flags.pyFlag )
        , ( "QA", Flags.qaFlag )
        , ( "RE", Flags.reFlag )
        , ( "RO", Flags.roFlag )
        , ( "RS", Flags.rsFlag )
        , ( "RU", Flags.ruFlag )
        , ( "RW", Flags.rwFlag )
        , ( "SA", Flags.saFlag )
        , ( "SB", Flags.sbFlag )
        , ( "SC", Flags.scFlag )
        , ( "SD", Flags.sdFlag )
        , ( "SE", Flags.seFlag )
        , ( "SG", Flags.sgFlag )
        , ( "SH", Flags.shFlag )
        , ( "SI", Flags.siFlag )
        , ( "SJ", Flags.sjFlag )
        , ( "SK", Flags.skFlag )
        , ( "SL", Flags.slFlag )
        , ( "SM", Flags.smFlag )
        , ( "SN", Flags.snFlag )
        , ( "SO", Flags.soFlag )
        , ( "SR", Flags.srFlag )
        , ( "SS", Flags.ssFlag )
        , ( "ST", Flags.stFlag )
        , ( "SV", Flags.svFlag )
        , ( "SX", Flags.sxFlag )
        , ( "SY", Flags.syFlag )
        , ( "SZ", Flags.szFlag )
        , ( "TC", Flags.tcFlag )
        , ( "TD", Flags.tdFlag )
        , ( "TG", Flags.tgFlag )
        , ( "TH", Flags.thFlag )
        , ( "TJ", Flags.tjFlag )
        , ( "TK", Flags.tkFlag )
        , ( "TL", Flags.tlFlag )
        , ( "TM", Flags.tmFlag )
        , ( "TN", Flags.tnFlag )
        , ( "TO", Flags.toFlag )
        , ( "TR", Flags.trFlag )
        , ( "TT", Flags.ttFlag )
        , ( "TV", Flags.tvFlag )
        , ( "TW", Flags.twFlag )
        , ( "TZ", Flags.tzFlag )
        , ( "UA", Flags.uaFlag )
        , ( "UG", Flags.ugFlag )
        , ( "US", Flags.usFlag )
        , ( "UY", Flags.uyFlag )
        , ( "UZ", Flags.uzFlag )
        , ( "VA", Flags.vaFlag )
        , ( "VC", Flags.vcFlag )
        , ( "VE", Flags.veFlag )
        , ( "VG", Flags.vgFlag )
        , ( "VI", Flags.viFlag )
        , ( "VN", Flags.vnFlag )
        , ( "VU", Flags.vuFlag )
        , ( "WF", Flags.wfFlag )
        , ( "WS", Flags.wsFlag )
        , ( "XK", Flags.xkFlag )
        , ( "YE", Flags.yeFlag )
        , ( "YT", Flags.ytFlag )
        , ( "ZA", Flags.zaFlag )
        , ( "ZM", Flags.zmFlag )
        , ( "ZW", Flags.zwFlag )
        ]
