#!/bin/bash
svgo --multipass -p 0 cy.svg
svgo --multipass -p 0 vi.svg
svgo --multipass -p 0 sz.svg
svgo --multipass -p 0 dm.svg
svgo --multipass -p 0 nf.svg
svgo --multipass -p 0 by.svg
svgo --multipass -p 0 bn.svg
svgo --multipass -p 0 ms.svg
svgo --multipass -p 0 zm.svg
svgo --multipass -p 0 io.svg
svgo --multipass -p 0 bz.svg
svgo --multipass -p 0 ki.svg
svgo --multipass -p 0 vg.svg
svgo --multipass -p 0 kz.svg
svgo --multipass -p 0 je.svg
svgo --multipass -p 0 mp.svg
svgo --multipass -p 0 um.svg
svgo --multipass -p 0 tm.svg
svgo --multipass -p 0 pf.svg
svgo --multipass -p 0 gq.svg
svgo --multipass -p 0 fk.svg
svgo --multipass -p 0 gu.svg
svgo --multipass -p 0 us.svg
svgo --multipass -p 0 vu.svg
svgo --multipass -p 0 ni.svg
svgo --multipass -p 0 mw.svg
svgo --multipass -p 0 ht.svg
svgo --multipass -p 0 bt.svg
svgo --multipass -p 0 ec.svg
svgo --multipass -p 0 ug.svg
svgo --multipass -p 0 kg.svg
svgo --multipass -p 0 gt.svg
svgo --multipass -p 0 er.svg
svgo --multipass -p 0 im.svg
svgo --multipass -p 0 al.svg
svgo --multipass -p 0 ir.svg
svgo --multipass -p 0 hk.svg
svgo --multipass -p 0 fj.svg
svgo --multipass -p 0 aq.svg
svgo --multipass -p 0 ar.svg
svgo --multipass -p 0 cc.svg
svgo --multipass -p 0 gi.svg
svgo --multipass -p 0 lb.svg
svgo --multipass -p 0 sh.svg
svgo --multipass -p 0 mz.svg
svgo --multipass -p 0 cx.svg
svgo --multipass -p 0 ai.svg
svgo --multipass -p 0 nz.svg
svgo --multipass -p 0 zw.svg
svgo --multipass -p 0 tv.svg
svgo --multipass -p 0 si.svg
svgo --multipass -p 0 tc.svg
svgo --multipass -p 0 ck.svg
svgo --multipass -p 0 do.svg
svgo --multipass -p 0 kr.svg
svgo --multipass -p 0 pn.svg
svgo --multipass -p 0 ge.svg
svgo --multipass -p 0 nu.svg
svgo --multipass -p 0 iq.svg
svgo --multipass -p 0 ky.svg
svgo --multipass -p 0 br.svg
svgo --multipass -p 0 ao.svg
svgo --multipass -p 0 pg.svg
svgo --multipass -p 0 me.svg
svgo --multipass -p 0 bm.svg
svgo --multipass -p 0 mt.svg
svgo --multipass -p 0 aw.svg
svgo --multipass -p 0 sa.svg
svgo --multipass -p 0 mo.svg
svgo --multipass -p 0 tj.svg
svgo --multipass -p 0 om.svg
svgo --multipass -p 0 sx.svg
svgo --multipass -p 0 bo.svg
svgo --multipass -p 0 as.svg
svgo --multipass -p 0 mx.svg
svgo --multipass -p 0 rs.svg
svgo --multipass -p 0 gd.svg
svgo --multipass -p 0 hm.svg
svgo --multipass -p 0 lk.svg
svgo --multipass -p 0 ba.svg
svgo --multipass -p 0 md.svg
svgo --multipass -p 0 au.svg
svgo --multipass -p 0 af.svg
svgo --multipass -p 0 uy.svg
svgo --multipass -p 0 ls.svg
svgo --multipass -p 0 cv.svg
svgo --multipass -p 0 sm.svg
svgo --multipass -p 0 hr.svg
svgo --multipass -p 0 py.svg
svgo --multipass -p 0 va.svg
svgo --multipass -p 0 sk.svg
svgo --multipass -p 0 mn.svg
svgo --multipass -p 0 pe.svg
svgo --multipass -p 0 sv.svg
svgo --multipass -p 0 kh.svg
svgo --multipass -p 0 li.svg
svgo --multipass -p 0 et.svg
svgo --multipass -p 0 pt.svg
svgo --multipass -p 0 my.svg
svgo --multipass -p 0 eg.svg
svgo --multipass -p 0 es.svg
svgo --multipass -p 0 uz.svg
svgo --multipass -p 0 ke.svg
svgo --multipass -p 0 np.svg
svgo --multipass -p 0 ph.svg
svgo --multipass -p 0 bi.svg
svgo --multipass -p 0 na.svg
svgo --multipass -p 0 km.svg
svgo --multipass -p 0 eu.svg
svgo --multipass -p 0 sg.svg
svgo --multipass -p 0 tw.svg
svgo --multipass -p 0 sb.svg
svgo --multipass -p 0 ve.svg
svgo --multipass -p 0 hn.svg
svgo --multipass -p 0 tf.svg
svgo --multipass -p 0 eh.svg
svgo --multipass -p 0 in.svg
svgo --multipass -p 0 za.svg
svgo --multipass -p 0 il.svg
svgo --multipass -p 0 mh.svg
svgo --multipass -p 0 kp.svg
svgo --multipass -p 0 tn.svg
svgo --multipass -p 0 gb.svg
svgo --multipass -p 0 kn.svg
svgo --multipass -p 0 fm.svg
svgo --multipass -p 0 ca.svg
svgo --multipass -p 0 st.svg
svgo --multipass -p 0 mr.svg
svgo --multipass -p 0 pk.svg
svgo --multipass -p 0 ag.svg
svgo --multipass -p 0 ws.svg
svgo --multipass -p 0 pa.svg
svgo --multipass -p 0 mm.svg
svgo --multipass -p 0 cn.svg
svgo --multipass -p 0 cm.svg
svgo --multipass -p 0 tg.svg
svgo --multipass -p 0 lr.svg
svgo --multipass -p 0 jo.svg
svgo --multipass -p 0 gr.svg
svgo --multipass -p 0 gw.svg
svgo --multipass -p 0 nr.svg
svgo --multipass -p 0 rw.svg
svgo --multipass -p 0 tk.svg
svgo --multipass -p 0 bb.svg
svgo --multipass -p 0 se.svg
svgo --multipass -p 0 cf.svg
svgo --multipass -p 0 pr.svg
svgo --multipass -p 0 cw.svg
svgo --multipass -p 0 tr.svg
svgo --multipass -p 0 cu.svg
svgo --multipass -p 0 tl.svg
svgo --multipass -p 0 sy.svg
svgo --multipass -p 0 fo.svg
svgo --multipass -p 0 bv.svg
svgo --multipass -p 0 dj.svg
svgo --multipass -p 0 cl.svg
svgo --multipass -p 0 gg.svg
svgo --multipass -p 0 bh.svg
svgo --multipass -p 0 ps.svg
svgo --multipass -p 0 bs.svg
svgo --multipass -p 0 sc.svg
svgo --multipass -p 0 gy.svg
svgo --multipass -p 0 tz.svg
svgo --multipass -p 0 ax.svg
svgo --multipass -p 0 gm.svg
svgo --multipass -p 0 az.svg
svgo --multipass -p 0 is.svg
svgo --multipass -p 0 vn.svg
svgo --multipass -p 0 so.svg
svgo --multipass -p 0 ly.svg
svgo --multipass -p 0 vc.svg
svgo --multipass -p 0 kw.svg
svgo --multipass -p 0 bj.svg
svgo --multipass -p 0 jp.svg
svgo --multipass -p 0 sd.svg
svgo --multipass -p 0 cg.svg
svgo --multipass -p 0 cz.svg
svgo --multipass -p 0 pw.svg
svgo --multipass -p 0 sn.svg
svgo --multipass -p 0 la.svg
svgo --multipass -p 0 lt.svg
svgo --multipass -p 0 bf.svg
svgo --multipass -p 0 jm.svg
svgo --multipass -p 0 qa.svg
svgo --multipass -p 0 lc.svg
svgo --multipass -p 0 ss.svg
svgo --multipass -p 0 mk.svg
svgo --multipass -p 0 to.svg
svgo --multipass -p 0 nl.svg
svgo --multipass -p 0 tt.svg
svgo --multipass -p 0 cd.svg
svgo --multipass -p 0 sr.svg
svgo --multipass -p 0 ch.svg
svgo --multipass -p 0 ee.svg
svgo --multipass -p 0 no.svg
svgo --multipass -p 0 sj.svg
svgo --multipass -p 0 mu.svg
svgo --multipass -p 0 ie.svg
svgo --multipass -p 0 ro.svg
svgo --multipass -p 0 be.svg
svgo --multipass -p 0 it.svg
svgo --multipass -p 0 nc.svg
svgo --multipass -p 0 pm.svg
svgo --multipass -p 0 re.svg
svgo --multipass -p 0 yt.svg
svgo --multipass -p 0 hu.svg
svgo --multipass -p 0 bl.svg
svgo --multipass -p 0 gl.svg
svgo --multipass -p 0 gn.svg
svgo --multipass -p 0 mg.svg
svgo --multipass -p 0 wf.svg
svgo --multipass -p 0 bg.svg
svgo --multipass -p 0 cr.svg
svgo --multipass -p 0 dz.svg
svgo --multipass -p 0 fr.svg
svgo --multipass -p 0 gp.svg
svgo --multipass -p 0 mf.svg
svgo --multipass -p 0 gh.svg
svgo --multipass -p 0 th.svg
svgo --multipass -p 0 mq.svg
svgo --multipass -p 0 ru.svg
svgo --multipass -p 0 ci.svg
svgo --multipass -p 0 co.svg
svgo --multipass -p 0 mv.svg
svgo --multipass -p 0 ml.svg
svgo --multipass -p 0 td.svg
svgo --multipass -p 0 ng.svg
svgo --multipass -p 0 ye.svg
svgo --multipass -p 0 sl.svg
svgo --multipass -p 0 ga.svg
svgo --multipass -p 0 ne.svg
svgo --multipass -p 0 gf.svg
svgo --multipass -p 0 bw.svg
svgo --multipass -p 0 ma.svg
svgo --multipass -p 0 es-ct.svg
svgo --multipass -p 0 ae.svg
svgo --multipass -p 0 fi.svg
svgo --multipass -p 0 id.svg
svgo --multipass -p 0 lv.svg
svgo --multipass -p 0 at.svg
svgo --multipass -p 0 dk.svg
svgo --multipass -p 0 gb-eng.svg
svgo --multipass -p 0 ua.svg
svgo --multipass -p 0 mc.svg
svgo --multipass -p 0 ad.svg
svgo --multipass -p 0 lu.svg
svgo --multipass -p 0 gb-sct.svg
svgo --multipass -p 0 pl.svg
svgo --multipass -p 0 bq.svg
svgo --multipass -p 0 am.svg
svgo --multipass -p 0 de.svg
svgo --multipass -p 0 bd.svg