module IntlPhoneInput.Flag.EU exposing (flag)

import Svg exposing (..)
import Svg.Attributes exposing (..)


flag : Svg msg
flag =
    svg [ height "100%", width "100%", viewBox "0 0 640 480" ]
        [ defs []
            [ g [ id "d" ]
                [ g [ id "b" ]
                    [ Svg.path [ d "M0-1v1z", id "a" ]
                        []
                    , use [ transform "scale(-1 1)", xlinkHref "#a" ]
                        []
                    ]
                , g [ id "c" ]
                    [ use [ transform "rotate(72)", xlinkHref "#b" ]
                        []
                    , use [ transform "rotate(144)", xlinkHref "#b" ]
                        []
                    ]
                , use [ transform "scale(-1 1)", xlinkHref "#c" ]
                    []
                ]
            ]
        , Svg.path [ fill "#039", d "M0 0h640v480H0z" ]
            []
        , g [ transform "translate(320 242) scale(23.7037)", fill "#fc0" ]
            [ use [ height "100%", width "100%", xlinkHref "#d", y "-6" ]
                []
            , use [ height "100%", width "100%", xlinkHref "#d", y "6" ]
                []
            , g [ id "e" ]
                [ use [ height "100%", width "100%", xlinkHref "#d", x "-6" ]
                    []
                , use [ height "100%", width "100%", xlinkHref "#d", transform "rotate(-144 -2 -2)" ]
                    []
                , use [ height "100%", width "100%", xlinkHref "#d", transform "rotate(144 -2 -2)" ]
                    []
                , use [ height "100%", width "100%", xlinkHref "#d", transform "rotate(72 -5 -2)" ]
                    []
                , use [ height "100%", width "100%", xlinkHref "#d", transform "rotate(72 -5 1)" ]
                    []
                ]
            , use [ height "100%", width "100%", xlinkHref "#e", transform "scale(-1 1)" ]
                []
            ]
        ]
