#!/bin/bash
cp -n Unknown.elm AD.elm; sed -i -e 's/Unknown/AD/g' AD.elm
cp -n Unknown.elm AE.elm; sed -i -e 's/Unknown/AE/g' AE.elm
cp -n Unknown.elm AF.elm; sed -i -e 's/Unknown/AF/g' AF.elm
cp -n Unknown.elm AG.elm; sed -i -e 's/Unknown/AG/g' AG.elm
cp -n Unknown.elm AI.elm; sed -i -e 's/Unknown/AI/g' AI.elm
cp -n Unknown.elm AL.elm; sed -i -e 's/Unknown/AL/g' AL.elm
cp -n Unknown.elm AM.elm; sed -i -e 's/Unknown/AM/g' AM.elm
cp -n Unknown.elm AO.elm; sed -i -e 's/Unknown/AO/g' AO.elm
cp -n Unknown.elm AR.elm; sed -i -e 's/Unknown/AR/g' AR.elm
cp -n Unknown.elm AS.elm; sed -i -e 's/Unknown/AS/g' AS.elm
cp -n Unknown.elm AT.elm; sed -i -e 's/Unknown/AT/g' AT.elm
cp -n Unknown.elm AU.elm; sed -i -e 's/Unknown/AU/g' AU.elm
cp -n Unknown.elm AW.elm; sed -i -e 's/Unknown/AW/g' AW.elm
cp -n Unknown.elm AX.elm; sed -i -e 's/Unknown/AX/g' AX.elm
cp -n Unknown.elm AZ.elm; sed -i -e 's/Unknown/AZ/g' AZ.elm
cp -n Unknown.elm BA.elm; sed -i -e 's/Unknown/BA/g' BA.elm
cp -n Unknown.elm BB.elm; sed -i -e 's/Unknown/BB/g' BB.elm
cp -n Unknown.elm BD.elm; sed -i -e 's/Unknown/BD/g' BD.elm
cp -n Unknown.elm BE.elm; sed -i -e 's/Unknown/BE/g' BE.elm
cp -n Unknown.elm BF.elm; sed -i -e 's/Unknown/BF/g' BF.elm
cp -n Unknown.elm BG.elm; sed -i -e 's/Unknown/BG/g' BG.elm
cp -n Unknown.elm BH.elm; sed -i -e 's/Unknown/BH/g' BH.elm
cp -n Unknown.elm BI.elm; sed -i -e 's/Unknown/BI/g' BI.elm
cp -n Unknown.elm BJ.elm; sed -i -e 's/Unknown/BJ/g' BJ.elm
cp -n Unknown.elm BL.elm; sed -i -e 's/Unknown/BL/g' BL.elm
cp -n Unknown.elm BM.elm; sed -i -e 's/Unknown/BM/g' BM.elm
cp -n Unknown.elm BN.elm; sed -i -e 's/Unknown/BN/g' BN.elm
cp -n Unknown.elm BO.elm; sed -i -e 's/Unknown/BO/g' BO.elm
cp -n Unknown.elm BQ.elm; sed -i -e 's/Unknown/BQ/g' BQ.elm
cp -n Unknown.elm BR.elm; sed -i -e 's/Unknown/BR/g' BR.elm
cp -n Unknown.elm BS.elm; sed -i -e 's/Unknown/BS/g' BS.elm
cp -n Unknown.elm BT.elm; sed -i -e 's/Unknown/BT/g' BT.elm
cp -n Unknown.elm BW.elm; sed -i -e 's/Unknown/BW/g' BW.elm
cp -n Unknown.elm BY.elm; sed -i -e 's/Unknown/BY/g' BY.elm
cp -n Unknown.elm BZ.elm; sed -i -e 's/Unknown/BZ/g' BZ.elm
cp -n Unknown.elm CA.elm; sed -i -e 's/Unknown/CA/g' CA.elm
cp -n Unknown.elm CC.elm; sed -i -e 's/Unknown/CC/g' CC.elm
cp -n Unknown.elm CD.elm; sed -i -e 's/Unknown/CD/g' CD.elm
cp -n Unknown.elm CF.elm; sed -i -e 's/Unknown/CF/g' CF.elm
cp -n Unknown.elm CG.elm; sed -i -e 's/Unknown/CG/g' CG.elm
cp -n Unknown.elm CH.elm; sed -i -e 's/Unknown/CH/g' CH.elm
cp -n Unknown.elm CI.elm; sed -i -e 's/Unknown/CI/g' CI.elm
cp -n Unknown.elm CK.elm; sed -i -e 's/Unknown/CK/g' CK.elm
cp -n Unknown.elm CL.elm; sed -i -e 's/Unknown/CL/g' CL.elm
cp -n Unknown.elm CM.elm; sed -i -e 's/Unknown/CM/g' CM.elm
cp -n Unknown.elm CN.elm; sed -i -e 's/Unknown/CN/g' CN.elm
cp -n Unknown.elm CO.elm; sed -i -e 's/Unknown/CO/g' CO.elm
cp -n Unknown.elm CR.elm; sed -i -e 's/Unknown/CR/g' CR.elm
cp -n Unknown.elm CU.elm; sed -i -e 's/Unknown/CU/g' CU.elm
cp -n Unknown.elm CV.elm; sed -i -e 's/Unknown/CV/g' CV.elm
cp -n Unknown.elm CW.elm; sed -i -e 's/Unknown/CW/g' CW.elm
cp -n Unknown.elm CX.elm; sed -i -e 's/Unknown/CX/g' CX.elm
cp -n Unknown.elm CY.elm; sed -i -e 's/Unknown/CY/g' CY.elm
cp -n Unknown.elm CZ.elm; sed -i -e 's/Unknown/CZ/g' CZ.elm
cp -n Unknown.elm DE.elm; sed -i -e 's/Unknown/DE/g' DE.elm
cp -n Unknown.elm DJ.elm; sed -i -e 's/Unknown/DJ/g' DJ.elm
cp -n Unknown.elm DK.elm; sed -i -e 's/Unknown/DK/g' DK.elm
cp -n Unknown.elm DM.elm; sed -i -e 's/Unknown/DM/g' DM.elm
cp -n Unknown.elm DO.elm; sed -i -e 's/Unknown/DO/g' DO.elm
cp -n Unknown.elm DZ.elm; sed -i -e 's/Unknown/DZ/g' DZ.elm
cp -n Unknown.elm EC.elm; sed -i -e 's/Unknown/EC/g' EC.elm
cp -n Unknown.elm EE.elm; sed -i -e 's/Unknown/EE/g' EE.elm
cp -n Unknown.elm EG.elm; sed -i -e 's/Unknown/EG/g' EG.elm
cp -n Unknown.elm EH.elm; sed -i -e 's/Unknown/EH/g' EH.elm
cp -n Unknown.elm ER.elm; sed -i -e 's/Unknown/ER/g' ER.elm
cp -n Unknown.elm ES.elm; sed -i -e 's/Unknown/ES/g' ES.elm
cp -n Unknown.elm ET.elm; sed -i -e 's/Unknown/ET/g' ET.elm
cp -n Unknown.elm FI.elm; sed -i -e 's/Unknown/FI/g' FI.elm
cp -n Unknown.elm FJ.elm; sed -i -e 's/Unknown/FJ/g' FJ.elm
cp -n Unknown.elm FK.elm; sed -i -e 's/Unknown/FK/g' FK.elm
cp -n Unknown.elm FM.elm; sed -i -e 's/Unknown/FM/g' FM.elm
cp -n Unknown.elm FO.elm; sed -i -e 's/Unknown/FO/g' FO.elm
cp -n Unknown.elm FR.elm; sed -i -e 's/Unknown/FR/g' FR.elm
cp -n Unknown.elm GA.elm; sed -i -e 's/Unknown/GA/g' GA.elm
cp -n Unknown.elm GB.elm; sed -i -e 's/Unknown/GB/g' GB.elm
cp -n Unknown.elm GD.elm; sed -i -e 's/Unknown/GD/g' GD.elm
cp -n Unknown.elm GE.elm; sed -i -e 's/Unknown/GE/g' GE.elm
cp -n Unknown.elm GF.elm; sed -i -e 's/Unknown/GF/g' GF.elm
cp -n Unknown.elm GG.elm; sed -i -e 's/Unknown/GG/g' GG.elm
cp -n Unknown.elm GH.elm; sed -i -e 's/Unknown/GH/g' GH.elm
cp -n Unknown.elm GI.elm; sed -i -e 's/Unknown/GI/g' GI.elm
cp -n Unknown.elm GL.elm; sed -i -e 's/Unknown/GL/g' GL.elm
cp -n Unknown.elm GM.elm; sed -i -e 's/Unknown/GM/g' GM.elm
cp -n Unknown.elm GN.elm; sed -i -e 's/Unknown/GN/g' GN.elm
cp -n Unknown.elm GP.elm; sed -i -e 's/Unknown/GP/g' GP.elm
cp -n Unknown.elm GQ.elm; sed -i -e 's/Unknown/GQ/g' GQ.elm
cp -n Unknown.elm GR.elm; sed -i -e 's/Unknown/GR/g' GR.elm
cp -n Unknown.elm GT.elm; sed -i -e 's/Unknown/GT/g' GT.elm
cp -n Unknown.elm GU.elm; sed -i -e 's/Unknown/GU/g' GU.elm
cp -n Unknown.elm GW.elm; sed -i -e 's/Unknown/GW/g' GW.elm
cp -n Unknown.elm GY.elm; sed -i -e 's/Unknown/GY/g' GY.elm
cp -n Unknown.elm HK.elm; sed -i -e 's/Unknown/HK/g' HK.elm
cp -n Unknown.elm HN.elm; sed -i -e 's/Unknown/HN/g' HN.elm
cp -n Unknown.elm HR.elm; sed -i -e 's/Unknown/HR/g' HR.elm
cp -n Unknown.elm HT.elm; sed -i -e 's/Unknown/HT/g' HT.elm
cp -n Unknown.elm HU.elm; sed -i -e 's/Unknown/HU/g' HU.elm
cp -n Unknown.elm ID.elm; sed -i -e 's/Unknown/ID/g' ID.elm
cp -n Unknown.elm IE.elm; sed -i -e 's/Unknown/IE/g' IE.elm
cp -n Unknown.elm IL.elm; sed -i -e 's/Unknown/IL/g' IL.elm
cp -n Unknown.elm IM.elm; sed -i -e 's/Unknown/IM/g' IM.elm
cp -n Unknown.elm IN.elm; sed -i -e 's/Unknown/IN/g' IN.elm
cp -n Unknown.elm IO.elm; sed -i -e 's/Unknown/IO/g' IO.elm
cp -n Unknown.elm IQ.elm; sed -i -e 's/Unknown/IQ/g' IQ.elm
cp -n Unknown.elm IR.elm; sed -i -e 's/Unknown/IR/g' IR.elm
cp -n Unknown.elm IS.elm; sed -i -e 's/Unknown/IS/g' IS.elm
cp -n Unknown.elm IT.elm; sed -i -e 's/Unknown/IT/g' IT.elm
cp -n Unknown.elm JE.elm; sed -i -e 's/Unknown/JE/g' JE.elm
cp -n Unknown.elm JM.elm; sed -i -e 's/Unknown/JM/g' JM.elm
cp -n Unknown.elm JO.elm; sed -i -e 's/Unknown/JO/g' JO.elm
cp -n Unknown.elm JP.elm; sed -i -e 's/Unknown/JP/g' JP.elm
cp -n Unknown.elm KE.elm; sed -i -e 's/Unknown/KE/g' KE.elm
cp -n Unknown.elm KG.elm; sed -i -e 's/Unknown/KG/g' KG.elm
cp -n Unknown.elm KH.elm; sed -i -e 's/Unknown/KH/g' KH.elm
cp -n Unknown.elm KI.elm; sed -i -e 's/Unknown/KI/g' KI.elm
cp -n Unknown.elm KM.elm; sed -i -e 's/Unknown/KM/g' KM.elm
cp -n Unknown.elm KN.elm; sed -i -e 's/Unknown/KN/g' KN.elm
cp -n Unknown.elm KP.elm; sed -i -e 's/Unknown/KP/g' KP.elm
cp -n Unknown.elm KR.elm; sed -i -e 's/Unknown/KR/g' KR.elm
cp -n Unknown.elm KW.elm; sed -i -e 's/Unknown/KW/g' KW.elm
cp -n Unknown.elm KY.elm; sed -i -e 's/Unknown/KY/g' KY.elm
cp -n Unknown.elm KZ.elm; sed -i -e 's/Unknown/KZ/g' KZ.elm
cp -n Unknown.elm LA.elm; sed -i -e 's/Unknown/LA/g' LA.elm
cp -n Unknown.elm LB.elm; sed -i -e 's/Unknown/LB/g' LB.elm
cp -n Unknown.elm LC.elm; sed -i -e 's/Unknown/LC/g' LC.elm
cp -n Unknown.elm LI.elm; sed -i -e 's/Unknown/LI/g' LI.elm
cp -n Unknown.elm LK.elm; sed -i -e 's/Unknown/LK/g' LK.elm
cp -n Unknown.elm LR.elm; sed -i -e 's/Unknown/LR/g' LR.elm
cp -n Unknown.elm LS.elm; sed -i -e 's/Unknown/LS/g' LS.elm
cp -n Unknown.elm LT.elm; sed -i -e 's/Unknown/LT/g' LT.elm
cp -n Unknown.elm LU.elm; sed -i -e 's/Unknown/LU/g' LU.elm
cp -n Unknown.elm LV.elm; sed -i -e 's/Unknown/LV/g' LV.elm
cp -n Unknown.elm LY.elm; sed -i -e 's/Unknown/LY/g' LY.elm
cp -n Unknown.elm MA.elm; sed -i -e 's/Unknown/MA/g' MA.elm
cp -n Unknown.elm MC.elm; sed -i -e 's/Unknown/MC/g' MC.elm
cp -n Unknown.elm MD.elm; sed -i -e 's/Unknown/MD/g' MD.elm
cp -n Unknown.elm ME.elm; sed -i -e 's/Unknown/ME/g' ME.elm
cp -n Unknown.elm MF.elm; sed -i -e 's/Unknown/MF/g' MF.elm
cp -n Unknown.elm MG.elm; sed -i -e 's/Unknown/MG/g' MG.elm
cp -n Unknown.elm MH.elm; sed -i -e 's/Unknown/MH/g' MH.elm
cp -n Unknown.elm MK.elm; sed -i -e 's/Unknown/MK/g' MK.elm
cp -n Unknown.elm ML.elm; sed -i -e 's/Unknown/ML/g' ML.elm
cp -n Unknown.elm MM.elm; sed -i -e 's/Unknown/MM/g' MM.elm
cp -n Unknown.elm MN.elm; sed -i -e 's/Unknown/MN/g' MN.elm
cp -n Unknown.elm MO.elm; sed -i -e 's/Unknown/MO/g' MO.elm
cp -n Unknown.elm MP.elm; sed -i -e 's/Unknown/MP/g' MP.elm
cp -n Unknown.elm MQ.elm; sed -i -e 's/Unknown/MQ/g' MQ.elm
cp -n Unknown.elm MR.elm; sed -i -e 's/Unknown/MR/g' MR.elm
cp -n Unknown.elm MS.elm; sed -i -e 's/Unknown/MS/g' MS.elm
cp -n Unknown.elm MT.elm; sed -i -e 's/Unknown/MT/g' MT.elm
cp -n Unknown.elm MU.elm; sed -i -e 's/Unknown/MU/g' MU.elm
cp -n Unknown.elm MV.elm; sed -i -e 's/Unknown/MV/g' MV.elm
cp -n Unknown.elm MW.elm; sed -i -e 's/Unknown/MW/g' MW.elm
cp -n Unknown.elm MX.elm; sed -i -e 's/Unknown/MX/g' MX.elm
cp -n Unknown.elm MY.elm; sed -i -e 's/Unknown/MY/g' MY.elm
cp -n Unknown.elm MZ.elm; sed -i -e 's/Unknown/MZ/g' MZ.elm
cp -n Unknown.elm NA.elm; sed -i -e 's/Unknown/NA/g' NA.elm
cp -n Unknown.elm NC.elm; sed -i -e 's/Unknown/NC/g' NC.elm
cp -n Unknown.elm NE.elm; sed -i -e 's/Unknown/NE/g' NE.elm
cp -n Unknown.elm NF.elm; sed -i -e 's/Unknown/NF/g' NF.elm
cp -n Unknown.elm NG.elm; sed -i -e 's/Unknown/NG/g' NG.elm
cp -n Unknown.elm NI.elm; sed -i -e 's/Unknown/NI/g' NI.elm
cp -n Unknown.elm NL.elm; sed -i -e 's/Unknown/NL/g' NL.elm
cp -n Unknown.elm NO.elm; sed -i -e 's/Unknown/NO/g' NO.elm
cp -n Unknown.elm NP.elm; sed -i -e 's/Unknown/NP/g' NP.elm
cp -n Unknown.elm NR.elm; sed -i -e 's/Unknown/NR/g' NR.elm
cp -n Unknown.elm NU.elm; sed -i -e 's/Unknown/NU/g' NU.elm
cp -n Unknown.elm NZ.elm; sed -i -e 's/Unknown/NZ/g' NZ.elm
cp -n Unknown.elm OM.elm; sed -i -e 's/Unknown/OM/g' OM.elm
cp -n Unknown.elm PA.elm; sed -i -e 's/Unknown/PA/g' PA.elm
cp -n Unknown.elm PE.elm; sed -i -e 's/Unknown/PE/g' PE.elm
cp -n Unknown.elm PF.elm; sed -i -e 's/Unknown/PF/g' PF.elm
cp -n Unknown.elm PG.elm; sed -i -e 's/Unknown/PG/g' PG.elm
cp -n Unknown.elm PH.elm; sed -i -e 's/Unknown/PH/g' PH.elm
cp -n Unknown.elm PK.elm; sed -i -e 's/Unknown/PK/g' PK.elm
cp -n Unknown.elm PL.elm; sed -i -e 's/Unknown/PL/g' PL.elm
cp -n Unknown.elm PM.elm; sed -i -e 's/Unknown/PM/g' PM.elm
cp -n Unknown.elm PR.elm; sed -i -e 's/Unknown/PR/g' PR.elm
cp -n Unknown.elm PS.elm; sed -i -e 's/Unknown/PS/g' PS.elm
cp -n Unknown.elm PT.elm; sed -i -e 's/Unknown/PT/g' PT.elm
cp -n Unknown.elm PW.elm; sed -i -e 's/Unknown/PW/g' PW.elm
cp -n Unknown.elm PY.elm; sed -i -e 's/Unknown/PY/g' PY.elm
cp -n Unknown.elm QA.elm; sed -i -e 's/Unknown/QA/g' QA.elm
cp -n Unknown.elm RE.elm; sed -i -e 's/Unknown/RE/g' RE.elm
cp -n Unknown.elm RO.elm; sed -i -e 's/Unknown/RO/g' RO.elm
cp -n Unknown.elm RS.elm; sed -i -e 's/Unknown/RS/g' RS.elm
cp -n Unknown.elm RU.elm; sed -i -e 's/Unknown/RU/g' RU.elm
cp -n Unknown.elm RW.elm; sed -i -e 's/Unknown/RW/g' RW.elm
cp -n Unknown.elm SA.elm; sed -i -e 's/Unknown/SA/g' SA.elm
cp -n Unknown.elm SB.elm; sed -i -e 's/Unknown/SB/g' SB.elm
cp -n Unknown.elm SC.elm; sed -i -e 's/Unknown/SC/g' SC.elm
cp -n Unknown.elm SD.elm; sed -i -e 's/Unknown/SD/g' SD.elm
cp -n Unknown.elm SE.elm; sed -i -e 's/Unknown/SE/g' SE.elm
cp -n Unknown.elm SG.elm; sed -i -e 's/Unknown/SG/g' SG.elm
cp -n Unknown.elm SH.elm; sed -i -e 's/Unknown/SH/g' SH.elm
cp -n Unknown.elm SI.elm; sed -i -e 's/Unknown/SI/g' SI.elm
cp -n Unknown.elm SJ.elm; sed -i -e 's/Unknown/SJ/g' SJ.elm
cp -n Unknown.elm SK.elm; sed -i -e 's/Unknown/SK/g' SK.elm
cp -n Unknown.elm SL.elm; sed -i -e 's/Unknown/SL/g' SL.elm
cp -n Unknown.elm SM.elm; sed -i -e 's/Unknown/SM/g' SM.elm
cp -n Unknown.elm SN.elm; sed -i -e 's/Unknown/SN/g' SN.elm
cp -n Unknown.elm SO.elm; sed -i -e 's/Unknown/SO/g' SO.elm
cp -n Unknown.elm SR.elm; sed -i -e 's/Unknown/SR/g' SR.elm
cp -n Unknown.elm SS.elm; sed -i -e 's/Unknown/SS/g' SS.elm
cp -n Unknown.elm ST.elm; sed -i -e 's/Unknown/ST/g' ST.elm
cp -n Unknown.elm SV.elm; sed -i -e 's/Unknown/SV/g' SV.elm
cp -n Unknown.elm SX.elm; sed -i -e 's/Unknown/SX/g' SX.elm
cp -n Unknown.elm SY.elm; sed -i -e 's/Unknown/SY/g' SY.elm
cp -n Unknown.elm SZ.elm; sed -i -e 's/Unknown/SZ/g' SZ.elm
cp -n Unknown.elm TC.elm; sed -i -e 's/Unknown/TC/g' TC.elm
cp -n Unknown.elm TD.elm; sed -i -e 's/Unknown/TD/g' TD.elm
cp -n Unknown.elm TG.elm; sed -i -e 's/Unknown/TG/g' TG.elm
cp -n Unknown.elm TH.elm; sed -i -e 's/Unknown/TH/g' TH.elm
cp -n Unknown.elm TJ.elm; sed -i -e 's/Unknown/TJ/g' TJ.elm
cp -n Unknown.elm TK.elm; sed -i -e 's/Unknown/TK/g' TK.elm
cp -n Unknown.elm TL.elm; sed -i -e 's/Unknown/TL/g' TL.elm
cp -n Unknown.elm TM.elm; sed -i -e 's/Unknown/TM/g' TM.elm
cp -n Unknown.elm TN.elm; sed -i -e 's/Unknown/TN/g' TN.elm
cp -n Unknown.elm TO.elm; sed -i -e 's/Unknown/TO/g' TO.elm
cp -n Unknown.elm TR.elm; sed -i -e 's/Unknown/TR/g' TR.elm
cp -n Unknown.elm TT.elm; sed -i -e 's/Unknown/TT/g' TT.elm
cp -n Unknown.elm TV.elm; sed -i -e 's/Unknown/TV/g' TV.elm
cp -n Unknown.elm TW.elm; sed -i -e 's/Unknown/TW/g' TW.elm
cp -n Unknown.elm TZ.elm; sed -i -e 's/Unknown/TZ/g' TZ.elm
cp -n Unknown.elm UA.elm; sed -i -e 's/Unknown/UA/g' UA.elm
cp -n Unknown.elm UG.elm; sed -i -e 's/Unknown/UG/g' UG.elm
cp -n Unknown.elm US.elm; sed -i -e 's/Unknown/US/g' US.elm
cp -n Unknown.elm UY.elm; sed -i -e 's/Unknown/UY/g' UY.elm
cp -n Unknown.elm UZ.elm; sed -i -e 's/Unknown/UZ/g' UZ.elm
cp -n Unknown.elm VA.elm; sed -i -e 's/Unknown/VA/g' VA.elm
cp -n Unknown.elm VC.elm; sed -i -e 's/Unknown/VC/g' VC.elm
cp -n Unknown.elm VE.elm; sed -i -e 's/Unknown/VE/g' VE.elm
cp -n Unknown.elm VG.elm; sed -i -e 's/Unknown/VG/g' VG.elm
cp -n Unknown.elm VI.elm; sed -i -e 's/Unknown/VI/g' VI.elm
cp -n Unknown.elm VN.elm; sed -i -e 's/Unknown/VN/g' VN.elm
cp -n Unknown.elm VU.elm; sed -i -e 's/Unknown/VU/g' VU.elm
cp -n Unknown.elm WF.elm; sed -i -e 's/Unknown/WF/g' WF.elm
cp -n Unknown.elm WS.elm; sed -i -e 's/Unknown/WS/g' WS.elm
cp -n Unknown.elm XK.elm; sed -i -e 's/Unknown/XK/g' XK.elm
cp -n Unknown.elm YE.elm; sed -i -e 's/Unknown/YE/g' YE.elm
cp -n Unknown.elm YT.elm; sed -i -e 's/Unknown/YT/g' YT.elm
cp -n Unknown.elm ZA.elm; sed -i -e 's/Unknown/ZA/g' ZA.elm
cp -n Unknown.elm ZM.elm; sed -i -e 's/Unknown/ZM/g' ZM.elm
cp -n Unknown.elm ZW.elm; sed -i -e 's/Unknown/ZW/g' ZW.elm