module IntlPhoneInput.Flag.IN exposing (flag)

import Svg exposing (..)
import Svg.Attributes exposing (..)


flag : Svg msg
flag =
    svg [ height "100%", width "100%", viewBox "0 0 640 480" ]
        [ Svg.path [ fill "#f93", d "M0 0h640v160H0z" ]
            []
        , Svg.path [ fill "#fff", d "M0 160h640v160H0z" ]
            []
        , Svg.path [ fill "#128807", d "M0 320h640v160H0z" ]
            []
        , g [ transform "matrix(3.2 0 0 3.2 320 240)" ]
            [ circle [ r "20", fill "#008" ]
                []
            , circle [ r "18", fill "#fff" ]
                []
            , circle [ r "4", fill "#008" ]
                []
            , g [ id "d" ]
                [ g [ id "c" ]
                    [ g [ id "b" ]
                        [ g [ id "a", fill "#008" ]
                            [ circle [ r "1", transform "rotate(8 -9 134)" ]
                                []
                            , Svg.path [ d "M0 18L1 7 0 2l-1 5 1 11z" ]
                                []
                            ]
                        , use [ height "100%", width "100%", xlinkHref "#a", transform "rotate(15)" ]
                            []
                        ]
                    , use [ height "100%", width "100%", xlinkHref "#b", transform "rotate(30)" ]
                        []
                    ]
                , use [ height "100%", width "100%", xlinkHref "#c", transform "rotate(60)" ]
                    []
                ]
            , use [ height "100%", width "100%", xlinkHref "#d", transform "rotate(120)" ]
                []
            , use [ height "100%", width "100%", xlinkHref "#d", transform "rotate(-120)" ]
                []
            ]
        ]
