module IntlPhoneInput.Flag.PH exposing (flag)

import Svg exposing (..)
import Svg.Attributes exposing (..)


flag : Svg msg
flag =
    svg [ height "100%", width "100%", viewBox "0 0 640 480" ]
        [ Svg.path [ fill "#0038a8", d "M0 0h640v240H0z" ]
            []
        , Svg.path [ fill "#ce1126", d "M0 240h640v240H0z" ]
            []
        , Svg.path [ d "M415.692 240L0 480V0", fill "#fff" ]
            []
        , g [ transform "translate(149.333 240) scale(5.33333)", fill "#fcd116" ]
            [ circle [ r "9" ]
                []
            , g [ id "d" ]
                [ g [ id "c" ]
                    [ g [ id "b" ]
                        [ Svg.path [ d "M-1 0l.062.062L0 0l-.938-.062z", transform "scale(19)" ]
                            []
                        , Svg.path [ id "a", d "M-.884.116l.05.05L0 0z", transform "scale(19.2381)" ]
                            []
                        , use [ height "100%", width "100%", xlinkHref "#a", transform "scale(1 -1)" ]
                            []
                        ]
                    , use [ height "100%", width "100%", xlinkHref "#b", transform "rotate(45)" ]
                        []
                    ]
                , use [ height "100%", width "100%", xlinkHref "#c", transform "rotate(90)" ]
                    []
                ]
            , use [ height "100%", width "100%", xlinkHref "#d", transform "scale(-1)" ]
                []
            , g [ transform "translate(-2.02)" ]
                [ g [ id "f", transform "translate(37.962)" ]
                    [ Svg.path [ id "e", d "M5 0L1.618 1.176l-.073 3.58-2.163-2.854-3.427 1.037L-2 0z" ]
                        []
                    , use [ height "100%", width "100%", xlinkHref "#e", transform "scale(1 -1)" ]
                        []
                    ]
                , use [ height "100%", width "100%", xlinkHref "#f", transform "rotate(120)" ]
                    []
                , use [ height "100%", width "100%", xlinkHref "#f", transform "rotate(-120)" ]
                    []
                ]
            ]
        ]
