module IntlPhoneInput.Flag.PH exposing (flag)

import Svg exposing (..)
import Svg.Attributes exposing (..)


flag : Svg msg
flag =
    svg [ height "100%", width "100%", viewBox "0 0 640 480" ]
        [ Svg.path [ fill "#0038a8", d "M0 0h640v240H0z" ]
            []
        , Svg.path [ fill "#ce1126", d "M0 240h640v240H0z" ]
            []
        , Svg.path [ d "M416 240L0 480V0", fill "#fff" ]
            []
        , g [ transform "translate(149 240) scale(5.33333)", fill "#fcd116" ]
            [ circle [ r "9" ]
                []
            , g [ id "d" ]
                [ g [ id "c" ]
                    [ g [ id "b" ]
                        [ Svg.path [ d "M-1 0h1-1z", transform "scale(19)" ]
                            []
                        , Svg.path [ id "a", d "M-1 0h1z", transform "scale(19.2381)" ]
                            []
                        , use [ height "100%", width "100%", xlinkHref "#a", transform "scale(1 -1)" ]
                            []
                        ]
                    , use [ height "100%", width "100%", xlinkHref "#b", transform "rotate(45)" ]
                        []
                    ]
                , use [ height "100%", width "100%", xlinkHref "#c", transform "rotate(90)" ]
                    []
                ]
            , use [ height "100%", width "100%", xlinkHref "#d", transform "scale(-1)" ]
                []
            , g [ transform "translate(-2)" ]
                [ g [ id "f", transform "translate(38)" ]
                    [ Svg.path [ id "e", d "M5 0L2 1v4l-3-3-3 1 2-3z" ]
                        []
                    , use [ height "100%", width "100%", xlinkHref "#e", transform "scale(1 -1)" ]
                        []
                    ]
                , use [ height "100%", width "100%", xlinkHref "#f", transform "rotate(120)" ]
                    []
                , use [ height "100%", width "100%", xlinkHref "#f", transform "rotate(-120)" ]
                    []
                ]
            ]
        ]
