module IntlPhoneInput.Flag.UZ exposing (flag)

import Svg exposing (..)
import Svg.Attributes exposing (..)


flag : Svg msg
flag =
    svg [ height "100%", width "100%", viewBox "0 0 640 480" ]
        [ Svg.path [ fill "#1eb53a", d "M0 320h640v160H0z" ]
            []
        , Svg.path [ fill "#0099b5", d "M0 0h640v160H0z" ]
            []
        , Svg.path [ fill "#ce1126", d "M0 153.6h640v172.8H0z" ]
            []
        , Svg.path [ fill "#fff", d "M0 163.2h640v153.6H0z" ]
            []
        , circle [ cx "134.4", cy "76.8", r "57.6", fill "#fff" ]
            []
        , circle [ cx "153.6", cy "76.8", r "57.6", fill "#0099b5" ]
            []
        , g [ transform "matrix(1.92 0 0 1.92 261.12 122.88)", fill "#fff" ]
            [ g [ id "e" ]
                [ g [ id "d" ]
                    [ g [ id "c" ]
                        [ g [ id "b" ]
                            [ Svg.path [ id "a", d "M0-6L-1.854-.294 1 .633" ]
                                []
                            , use [ height "100%", width "100%", xlinkHref "#a", transform "scale(-1 1)" ]
                                []
                            ]
                        , use [ height "100%", width "100%", xlinkHref "#b", transform "rotate(72)" ]
                            []
                        ]
                    , use [ height "100%", width "100%", xlinkHref "#b", transform "rotate(-72)" ]
                        []
                    , use [ height "100%", width "100%", xlinkHref "#c", transform "rotate(144)" ]
                        []
                    ]
                , use [ height "100%", width "100%", xlinkHref "#d", y "-24" ]
                    []
                , use [ height "100%", width "100%", xlinkHref "#d", y "-48" ]
                    []
                ]
            , use [ height "100%", width "100%", xlinkHref "#e", x "24" ]
                []
            , use [ height "100%", width "100%", xlinkHref "#e", x "48" ]
                []
            , use [ height "100%", width "100%", xlinkHref "#d", x "-48" ]
                []
            , use [ height "100%", width "100%", xlinkHref "#d", x "-24" ]
                []
            , use [ height "100%", width "100%", xlinkHref "#d", x "-24", y "-24" ]
                []
            ]
        ]
